---

inventory:
    plugin: SimpleInventory
    options:
        host_file: "inventory/gnsmiko_hosts.yaml"
        group_file: "inventory/groups.yaml"
        defaults_file: "inventory/gns3_defaults.yaml"